version: '3.8'

services:
  mysql:
    container_name: collegehub-mysql
    image: mysql:8.0.30
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=collegehub
      - MYSQL_USER=collegehub
      - MYSQL_PASSWORD=12345678
    ports:
      - 3306:3306
    networks:
      - collegehub-network
    volumes:
      - ./mysql:/var/lib/mysql
  
  api:
    container_name: collegehub-api
    restart: unless-stopped
    image: collegehub-api:1.0.0
    build: 
      context: ./service
      dockerfile: Dockerfile
    environment:
      - CONNECTION_STRING=server=collegehub-mysql;user=root;password=12345678;database=hub
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - MAIL_ACCOUNT=berkslv@gmail.com,
      - MAIL_USERNAME=berkslv@gmail.com,
      - MAIL_PASSWORD=<my-sendinblue-password>,
      - MAIL_HOST=smtp-relay.sendinblue.com,
      - TOKEN_AUDIENCE=https://localhost:5001,
      - TOKEN_ISSUER=https://localhost:5001,
      - TOKEN_ACCESS_TOKEN_EXPIRATION=1000,
      - TOKEN_SECURITY_KEY=Erxkqb9amTxauDvpr
    ports:
      - 5001:5000
      - 5002:5001
    networks:
      - collegehub-network
    depends_on:
      - mysql

  client:
    container_name: collegehub-client
    restart: unless-stopped
    image: collegehub-client:1.0.0
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5001/api
    ports:
      - 3000:80
    networks:
      - collegehub-network
    depends_on:
      - service


networks:
  collegehub-network:
